name: Artifacts
on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  artifact:
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate artifact
        run: |
          zip artifact.zip -r package.json
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: artifact.zip

