name: Artifacts
on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  artifact:
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate artifact
        run: |
          zip artifact.zip -r package.json
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact.zip
          path: artifact.zip
      - name: Attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: '${{ github.workspace }}/artifact.zip'
