name: Build
on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  test1:
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    container: node:20.17-bookworm
    defaults:
      run:
        shell: bash
    steps:
      - name: Checks
        run: |
          pwd
          ls -la
          ls -ld /opt
          git config --list

      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install 
      
      - name: Check
        run: |
          pwd
          ls -la
          ls -ld /opt
          git config --list

  test2:
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    defaults:
      run:
        shell: bash

    steps:
      - name: Checks
        run: |
          pwd
          ls -la
          ls -ld /opt
          git config --list

      - name: Checkout
        uses: actions/checkout@v4

      - run: npm install 

      - name: Check
        run: |
          pwd
          ls -la
          ls -ld /opt
          git config --list
